#
# Event Info Bot - Bot service software for Telegram and Twitter to provide user with
#                  reminders of event date and info on request
#
# Copyright (C) 2019 Tiktaalik (Rodrigo Gambra-Middleton)
#                    Address your enquiries to: info@tiktaalik.dev
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Set version
# __version__ = (1, 0, 0)

# Configure bot for Google App Engine
runtime: python37

handlers:
  - url: /favicon\.ico
    static_files: public_html/static/images/favicon.ico
    upload: public_html/static/images/favicon\.ico
    secure: always
    redirect_http_response_code: 301

  - url: /robots.txt
    static_files: public_html/robots.txt
    upload: public_html/robots\.txt
    secure: always
    redirect_http_response_code: 301

  - url: /static
    static_dir: public_html/static
    secure: always
    redirect_http_response_code: 301

  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301

